name: Auto merge dependabot

on:
  pull_request:
    branches:
      - master

jobs:
  auto-merge-dependabot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        ## https://github.com/ahmadnassri/action-dependabot-auto-merge
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: patch
          github-token: ${{ secrets.GITHUB_TOKEN  }}
