name: CI

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - develop
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger Job
      uses: appleboy/gitlab-ci-action@master
      with:
        url: "https://gitlab.esss.lu.se/api/v4/projects/1903/trigger/pipeline"
        token: ${{ secrets.TOKEN }}
        project_id: 1903
        host: "gitlab.esss.se"
        ref: "master"
        debug: true
