name: CI

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - develop
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Trigger GitLab CI
        uses: appleboy/gitlab-ci-action@0.0.1
        with:
          url: "https://gitlab.esss.lu.se/api/v4/projects/1805/trigger/pipeline"
          token: ${{ secrets.TOKEN }}
          project_id: 100

