name: CI

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - develop
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@v1
      with:
        args:  -X POST -F token=${{secrets.TOKEN}} -ref="master" "https://gitlab.esss.lu.se/api/v4/projects/1903/trigger/pipeline"

