name: CI

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - develop
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      steps:
      - name: curl
        uses: wei/curl@v1
        with:
          args: -X POST -F ${{ secrets.TOKEN }} "https://gitlab.esss.lu.se/api/v4/projects/1805/trigger/pipeline"

