name: Test && Build

on:
  pull_request:
    branches: [master]

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Unit tests
        run: |
          npm install
          npm run test


  apitests:
    name: API tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: API tests
        env:
          MONGODB_URI: mongodb://mongodb:27017/scicat
          EXPRESS_SESSION_SECRET: a_scicat_secret
          JWT_SECRET: a_scicat_secret
          PORT: 3000
          HTTP_MAX_REDIRECTS: 5
          HTTP_TIMEOUT: 5000
          JWT_EXPIRES_IN: 3600
          SITE: SAMPLE-SITE
          PID_PREFIX: PID.SAMPLE.PREFIX
          DOI_PREFIX: DOI.SAMPLE.PREFIX
          METADATA_KEYS_RETURN_LIMIT: 100
          METADATA_PARENT_INSTANCES_RETURN_LIMIT: 100
        run: |
          npm install
          npm run api:after:start

  e2etests:
    name: E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run stack in docker-compose
        run: |
          cp CI/E2E/docker-compose.yaml docker-compose.yaml
          docker-compose pull
          docker-compose build --no-cache
          docker-compose up &

      - name: Checkout frontend repo
        uses: actions/checkout@v3
        with:
          repository: scicatproject/frontend
          path: frontend
          fetch-depth: 1

      - name: Run Cypress tests
        uses: cypress-io/github-action@v4
        with:
          working-directory: frontend
          config-file: CI/ESS/e2e/cypress.nestjs.json
          install-command: npm install --omit peer
          browser: chrome

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: frontend/cypress/screenshots/

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos
          path: frontend/cypress/videos/

  build:
    name: Build and push Docker image with branch tag
    runs-on: ubuntu-latest
    needs: [test, e2etests]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/scicatproject/scicat-backend-next
          flavor: |
            latest=false
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # For debugging capture the selected branch
      - name: Branch
        run: echo "Branch ${{ github.head_ref }}"

      # Replace all slashes with underscore because github container registry does't accept slashes as valid tag names
      - name: Extract branch name without slashes
        id: extract_branch
        shell: bash
        run: |
          # Extract branch name
          BRANCH_NAME=${{ github.head_ref }}

          # set output variable accessible in the action
          echo ::set-output name=branch::${BRANCH_NAME} | sed 's/\//\_/g'

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/scicatproject/backend-next:${{ steps.extract_branch.outputs.branch }}
