name: Unit tests

on: [push, pull_request]

jobs:
    test:
        name: Unit Tests
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Run tests in docker-compose
              run: |
                cp CI/ESS/docker-compose.gitlab.yaml docker-compose.yaml
                docker-compose down --remove-orphans
                docker-compose pull
                docker-compose build --no-cache
                docker-compose up --exit-code-from catamel
                docker-compose down
