version: "3.2"
services:
  mongodb:
    image: "bitnami/mongodb:latest"
    volumes:
      - "mongodb_data:/bitnami"
  scichat-loopback:
    image: "dacat/scichat-loopback:e2e"
    command: ["./wait-for-it.sh", "mongodb:27017", "--", "node", "-r", "dotenv/config", "."]
    volumes:
      - "./CI/ESS/.env:/home/node/app/.env"
    depends_on:
      - mongodb
  scicat-backend:
    image: "scicatproject/backend:e2e-test"
    environment: 
      - SCICHAT_URL
    depends_on:
      - mongodb
      - scichat-loopback
  scicat-frontend:
    build:
      context: .
      dockerfile: CI/ESS/Dockerfile.e2e
    command: ["./wait-for-it.sh", "scicat-backend:3000", "--", "nginx", "-g", "daemon off;"]
    depends_on:
      - scicat-backend
  cypress:
    build:
      context: .
      dockerfile: CI/ESS/Dockerfile.cypress
    command: ["./wait-for-it.sh", "scicat-frontend:80", "--", "npx", "cypress", "run", "--browser", "chrome"]
    depends_on:
      - scicat-frontend
volumes:
  mongodb_data:
    driver: local
