version: "3"
services:
  reverse-proxy:
    image: traefik
    command: --api --docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes: /var/run/docker.sock:/var/run/docker.sock
  mongodb:
    image: "bitnami/mongodb:latest"
    ports:
      - "27017:27017"
    volumes:
      - "mongodb_data:/bitnami"
  openldap:
    image: osixia/openldap
    container_name: openldap
    hostname: openldap
    environment:
      LDAP_ORGANISATION: "LDAP Catamel Auth"
      LDAP_SSL_HELPER_PREFIX: "ldap"
      LDAP_TLS_VERIFY_CLIENT: "never"
      LDAP_LOG_LEVEL: 256
      LDAP_ADMIN_PASSWORD: "admin"
    ports:
      - "389:389"
  openldap-seed:
    image: osixia/openldap
    volumes:
      - ./CI/ESS/ldif_files:/ldif_files
    links:
      - openldap
    entrypoint: sh -c '/ldif_files/addAll.sh'
  openldap-admin:
    image: osixia/phpldapadmin
    container_name: openldap-admin
    hostname: openldap-admin
    environment:
      PHPLDAPADMIN_HTTPS=false:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
    ports:
      - "8080:80"
    links:
      - "openldap:openldap"
    depends_on:
      - openldap
  catanie:
    image: "dacat/catanie:latest"
    ports:
      - "4200:80"
    labels:
      - "traefik.frontend.rule=PathPrefix:/"
      - "traefik.port=80"
  cataniecypress:
    image: "dacat/catanie:cypress"
    command: ["npx", "cypress", "run"]
    depends_on:
      - mongodb
      - catamel
      - catanie
      - openldap-seed
    links:
      - mongodb
      - catamel
      - catanie
      - openldap
  catamel:
    image: "dacat/catamel"
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - openldap-seed
    links:
      - mongodb
      - openldap
      - openldap-seed
    labels:
      - "traefik.frontend.rule=PathPrefix:/api, /auth"
      - "traefik.port=3000"
volumes:
  mongodb_data:
    driver: local
