version: "3.2"
services:
  mongodb:
    image: "bitnami/mongodb:latest"
    volumes:
      - "mongodb_data:/bitnami"
  catamel:
    image: "dacat/catamel"
    depends_on:
      - mongodb
  catanie:
    image: "dacat/catanie:e2e"
    command: ["./wait-for-it.sh", "catamel:3000", "--", "nginx", "-g", "daemon off;"]
    depends_on:
      - catamel
  cypress:
    image: "dacat/catanie:cypress"
    command: ["./wait-for-it.sh", "catanie:80", "--", "npx", "cypress", "run"]
    depends_on:
      - catanie
volumes:
  mongodb_data:
    driver: local
