version: "3"
services:
    mongodb:
        image: "bitnami/mongodb:4.0"
    catamel:
        build:
            context: .
            dockerfile: CI/ESS/Dockerfile.test
        depends_on:
            - mongodb
