version: "3.2"

services:
  reverse-proxy:
    image: traefik:v2.0
    command: --api.insecure=true --providers.docker=true --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  catanie-test:
    # image: "docker.maxiv.lu.se/catanie-test"
    image: "catanie-local"
    restart: always
    ports:
      - "3002:80"
  catamel-test:
    # image: "docker.maxiv.lu.se/catamel-test"
    image: "catamel-local"
    restart: always
    ports:
      - "3001:3000"
