version: "3.2"
services:
  reverse-proxy:
    image: traefik:2.5
    command: --api.insecure=true --providers.docker=true --entrypoints.web.address=:80
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mongodb:
    image: "bitnami/mongodb:latest"
    volumes:
      - "mongodb_data:/bitnami"
  scichat-loopback:
    image: "dacat/scichat-loopback:e2e"
    command: ["./wait-for-it.sh", "mongodb:27017", "--", "node", "-r", "dotenv/config", "."]
    volumes:
      - "./CI/ESS/e2e/.env:/home/node/app/.env"
    depends_on:
      - mongodb
  catamel:
    image: "dacat/catamel:latest"
    environment: 
      - SCICHAT_URL
    ports:
      - 3000:3000
    depends_on:
      - mongodb
      - scichat-loopback
    labels:
      - "traefik.http.routers.catamel.rule=PathPrefix(`/api/v3`, `/auth/msad`)"
      - "traefik.http.routers.catamel.entrypoints=web"
  catanie:
    build:
      context: .
      dockerfile: CI/ESS/e2e/Dockerfile.e2e
    command: ["./wait-for-it.sh", "catamel:3000", "--", "nginx", "-g", "daemon off;"]
    ports:
      - 4200:80
    volumes:
      - "./CI/ESS/e2e/config.e2e.json:/usr/share/nginx/html/assets/config.json"
      - "./CI/ESS/site.png:/usr/share/nginx/html/assets/images/site.png"
      - "./CI/ESS/site-logo.png:/usr/share/nginx/html/assets/images/site-logo.png"
      - "./CI/ESS/favicon.ico:/usr/share/nginx/html/favicon.ico"
    depends_on:
      - catamel
    labels:
      - "traefik.http.routers.catanie.rule=PathPrefix(`/`)"
      - "traefik.http.routers.catanie.entrypoints=web"
  # cypress:
  #   build:
  #     context: .
  #     dockerfile: CI/ESS/e2e/Dockerfile.cypress
  #   command: ["./wait-for-it.sh", "catanie:80", "--", "npx", "cypress", "run"]
  #   depends_on:
  #     - catanie
volumes:
  mongodb_data:
    driver: local
