name: Build && Push

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          registry: ghcr.io
          tags: latest
          image: scicatproject/frontend
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  gitlab:
    name: Deploy
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger ESS pipeline
        uses: appleboy/gitlab-ci-action@master
        with:
          token: ${{ secrets.TOKEN }}
          project_id: 1805
          ref: "master"
          host: "https://gitlab.esss.lu.se"
          debug: true

      - name: Trigger MAXIV pipeline
        uses: appleboy/gitlab-ci-action@master
        with:
          token: ${{ secrets.MAXIV_TOKEN }}
          project_id: 21902377
          ref: "develop"
          host: "https://gitlab.com"
          debug: true
