name: Build release

on:
  release:
    tags:
      - 'v*'
    types: 
      - created

jobs:
  build-release:
    name: Build release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create image tags
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: | 
            ghcr.io/${{ github.repository }}
            scicatproject/frontend
          flavor: latest=false
          tags: |
            type=raw,value=stable
            type=ref,event=tag

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
