name: CI

on: [push, pull_request]

jobs:
  unittest:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install and run tests
        run: |
          npm ci
          npm test

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  e2etests:
    name: E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run docker-compose
        run: |
          cp CI/ESS/cypress.json cypress.json
          cp CI/ESS/docker-compose.e2e.yaml docker-compose.yaml
          docker-compose pull
          docker-compose build --no-cache --parallel
          docker-compose up --exit-code-from cypress

  gitlab:
    name: Build and deploy
    needs: [unittest, e2etests]
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger ESS pipeline
        uses: appleboy/gitlab-ci-action@master
        with:
          token: ${{ secrets.TOKEN }}
          project_id: 1805
          ref: "master"
          host: "https://gitlab.esss.lu.se"
          debug: true

      - name: Trigger MAXIV pipeline
        uses: appleboy/gitlab-ci-action@master
        with:
          token: ${{ secrets.MAXIV_TOKEN }}
          project_id: 21902377
          ref: "develop"
          host: "https://gitlab.com"
          debug: true
