name: Test

on: [push, pull_request]

jobs:
  unittest:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install and run tests
        run: |
          npm ci
          npm test

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  
  cypress:
    name: Build and push cypress image
    needs: [unittest]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy cypress files
        run: |
          cp CI/ESS/Dockerfile.cypress Dockerfile.cypress
          cp CI/ESS/cypress.json cypress.json
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push cypress image
        id: docker_cypress_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.cypress
          push: true
          tags: dacat/catanie:cypress

  e2etests:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: [cypress]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run docker-compose
        run: |
          cp CI/ESS/docker-compose.e2e.yaml docker-compose.yaml
          docker-compose pull
          docker-compose up --build --exit-code-from cypress
